export const giftCards = [
  { name: "Amazon", code: "AMZ", icon: "/giftcard-icons/amazon.png" },
  { name: "Apple", code: "APL", icon: "/giftcard-icons/apple.svg" },
  { name: "Google Play", code: "GPL", icon: "/giftcard-icons/google-play.svg" },
  { name: "Steam", code: "STM", icon: "/giftcard-icons/steam.svg" },
  { name: "Xbox", code: "XBX", icon: "/giftcard-icons/xbox.png" },
  { name: "Razer Gold", code: "RZR", icon: "/giftcard-icons/razer-gold.svg" },
  { name: "Sephora", code: "SEP", icon: "/giftcard-icons/sephora.png" },
  { name: "eBay", code: "EBY", icon: "/giftcard-icons/ebay.svg" },
  { name: "American Express (Amex)", code: "AMX", icon: "/giftcard-icons/amex.svg" },
  { name: "Vanilla/OneVanilla Visa", code: "VAN", icon: "/giftcard-icons/van.svg" },
  { name: "Vanilla/OneVanilla Mastercard", code: "VMC", icon: "/giftcard-icons/vmc.svg" },
  { name: "Walmart Visa", code: "WMV", icon: "/giftcard-icons/wmv.svg" },
  { name: "Nordstrom", code: "NDS", icon: "/giftcard-icons/nds.svg" },
  { name: "Nike", code: "NKE", icon: "/giftcard-icons/nke.svg" },
  { name: "Macy", code: "MCY", icon: "/giftcard-icons/mcy.svg" },
  { name: "American Express", code: "AME", icon: "/giftcard-icons/ame.svg" },
  { name: "Footlocker", code: "FTL", icon: "/giftcard-icons/ftl.svg" },
  { name: "JCPenney", code: "JCP", icon: "/giftcard-icons/jcp.svg" },
  { name: "Target", code: "TGT", icon: "/giftcard-icons/tgt.svg" },
  { name: "American Express Serve", code: "AEXS", icon: "/giftcard-icons/aexs.svg" },
  { name: "Razer", code: "RZR2", icon: "/giftcard-icons/rzr2.svg" },
  { name: "Walmart", code: "WMT", icon: "/giftcard-icons/wmt.svg" },
  { name: "Visa", code: "VIS", icon: "/giftcard-icons/vis.svg" },
  { name: "Netspend", code: "NET", icon: "/giftcard-icons/net.svg" },
  { name: "Gamestop", code: "GMS", icon: "/giftcard-icons/gms.svg" },
  { name: "Kohl's", code: "KOH", icon: "/giftcard-icons/koh.svg" },
  { name: "Ulta Beauty", code: "ULT", icon: "/giftcard-icons/ult.svg" },
  { name: "Lowe's", code: "LOW", icon: "/giftcard-icons/low.svg" },
] as const;
